app_processes = ['aCTCRICFetcher',
                 'aCTATLASStatus',
                 'aCTATLASStatusCondor',
                 'aCTAutopilot',
                 'aCTAutopilotSent',
                 'aCTPandaGetJobs',
                 'aCTPanda2Arc',
                 'aCTPanda2Condor',
                 'aCTValidator',
                 'aCTValidatorCondor']
